### ISSUE TITLE
rewrite-cljs

### ISSUE THREAD

**Issue by PEZ** [clj-commons/meta#12]
[rewrite-cljs](/rundis/rewrite-cljs) is a library I constantly find being used by libraries I use. It is almost a plugin-replacement of [rewrite-clj](/xsc/rewrite-clj).

The project seems rather abandoned, issues not being commented. I think it is WAY too important to leave in that state.

It might not be that it should be made a clj-commons project, as maybe what would be best is to make `rewrite-clj` a CLJC project instead. (Maybe the author of `rewrite-clj` would be interesting in ”securing” that project under this umbrella, but that is another matter.) In any case, maybe the undertaking of back-porting `rewrite-cljs` could be something that `clj-commons` can assist with?. I am almost ready to sign up to do most of the actual work, but only almost as a I am really spreading myself thin already.

**Comment by lread** [comment]
I would consider helping with this. I think [the authors of both rewrite-clj and rewrite-cljs agree a merge is interesting but neither has the time](https://github.com/xsc/rewrite-clj/issues/4).

**Comment by slipset** [comment]
I can contact @rundis and see what he thinks.

**Comment by lread** [comment]
It might be interesting to contact @xsc as well, [he was at one pointing look for a new maintainer](https://github.com/xsc/rewrite-clj/issues/4#issuecomment-189284923).

**Comment by slipset** [comment]
Thanks, @rundis :)

**Comment by danielcompton** [comment]
Do we have anyone willing to continue maintaining rewrite-cljs? @PEZ are you interested?

**Comment by danielcompton** [comment]
@lread you seem to be engaged with both projects, would you like commit access?

**Comment by lread** [comment]
Hi @danielcompton, thanks for thinking of me. Although I have decades of experience as a software developer, I am relatively new to Clojure & ClojureScript. That said, Clojure and the Clojure community are so very pleasant that I feel compelled to give back. So sure, sign me up!

@rundis do you have any notes, tips or todos relating to rewrite-cljs for us?

**Comment by lread** [comment]
I am working on a change for cljfmt and would like to use a feature that is in rewrite-clj that is not yet in rewrite-cljs. Moving forward, as @PEZ suggested, it seems that making rewrite-clj a cljc project could make sense. 

Perhaps, I could take a stab at this under rewrite-cljs. 

Does this make sense to others? Anybody have concerns or objections? @xsc what do you think?

**Comment by lread** [comment]
Found some an old blog entry from @rundis which is helpful in understanding some deviations from rewrite-clj: http://rundis.github.io/blog/2015/clojurescript_performance_tuning.html

**Comment by seancorfield** [comment]
Since `rewrite-clj` got forked to `clj-commons/rewrite-cljs`, it seems like this could be closed?

**Comment by PEZ** [comment]
Yeah, this seems to have happened. :smile:
