### ISSUE TITLE
saml20-clj

### ISSUE THREAD

**Issue by viesti** [clj-commons/meta#18]
There are quite many forks of [vlacs/saml20-clj](https://github.com/vlacs/saml20-clj/network/members), a [SAML20](https://en.wikipedia.org/wiki/SAML_2.0) library that one can plug into a Clojure/Ring application. Having a single version with fixes/enhancements incorporated from these multiple forks would make it easier to choose and use this library.

**Comment by slipset** [comment]
Let's see if @jrdoane would be interested in such a transfer. I don't think I'd have the capacity to consolidate all the different versions, so any help here would be greatly appreciated

**Comment by seancorfield** [comment]
@viesti @jrdoane @slipset -- any traction on this?

**Comment by slipset** [comment]
Not really, but I'm starting to use clj-saml at work, and I picked up the one that metabase is using  `[metabase/saml20-clj "1.0.2"]` as I figured they were actively using saml in their product.

Maybe @sbelak has some input?

**Comment by sbelak** [comment]
We came to the same conclusion -- none of the existing versions was maintained enough for us to be willing to depend on it and waiting for upstream to merge our bug fixes started to impede our releases, so we forked. We're pretty conservative with switching libraries, so we'll very likely stick with our fork for the foreseeable future.

**Comment by slipset** [comment]
Then I suggest we close this issue and recommend using `metabase/saml20-clj`
