### ISSUE TITLE
damballa/abracad

### ISSUE THREAD

**Issue by BrunoBonacci** [clj-commons/meta#21]
https://github.com/damballa/abracad is a wrapper for Avro.

It appears to be abandoned as people complained in this PR https://github.com/damballa/abracad/pull/32

There is also a fork https://github.com/ovotech/abracad as an effort to keep it up-to-date.
So maybe we can convince the owners to move it to clj-commons and fork's maintainer to push the updates.

**Comment by seancorfield** [comment]
@BrunoBonacci have you reached out to @ovotech to see whether they'd be interested in moving it to clj-commons?

**Comment by iku000888** [comment]
Nubank also maintains a version https://github.com/nubank/abracad

**Comment by slipset** [comment]
I think that if nubank has a maintained version, we should be supporting and using that.
