### ISSUE TITLE
Fork cemerick/url

### ISSUE THREAD

**Issue by oporkka** [clj-commons/meta#22]
The handy library https://github.com/cemerick/url is not anymore maintained (see https://github.com/cemerick/url/issues/30), and now also archived. It is a useful library for URL-handling, however, and I think it needs a new home.

It needs at least small patches like https://github.com/cemerick/url/pull/29

**Comment by piotr-yuxuan** [comment]
Also, you can try https://github.com/wtetzner/exploding-fish

**Comment by seancorfield** [comment]
There's a more up-to-date fork of `url` here https://github.com/arohner/uri but neither that nor the original look like they satisfy the entry criteria for clj-commons (not exactly popular/widely-depended on). The same goes for exploding-fish (seems unmaintained but not exactly popular/widely-depended on).
