### ISSUE TITLE
Lokeh/plum

### ISSUE THREAD

**Issue by lilactown** [clj-commons/meta#28]
I'm posting this here now to begin consideration of moving a small utility I started, [plum](https://github.com/Lokeh/plum), into clj-commons.

The basic idea behind it is to provide a packaging of standard `clojure` aliases for doing common operations on a project. Generating a new application, installing dependencies, running tests, etc.

More discussion can be found [in the thread on ClojureVerse](https://clojureverse.org/t/idea-a-tool-for-helping-developers-get-started-using-clojure-cli-tools-and-deps-edn/4270/21).

I think this would be a good candidate for clj-commons to encourage community contributions.

**Comment by danielcompton** [comment]
Thanks for opening discussion of this, plum looks like a really neat tool, and fits a missing gap.

I don't know if it meets the [entry criteria](https://github.com/clj-commons/wishlist#entry-criteria) for a project, as it is very new and still maintained by you? What would having this in clj-commons do for community contributions that you couldn't get in the existing project?

**Comment by seancorfield** [comment]
@Lokeh Any thoughts on @danielcompton 's comments/questions from three months ago?

**Comment by seancorfield** [comment]
@lilactown This seems to have died on the vine... as Daniel said four years ago, this probably doesn't meet the entry requirements and, at this point, it feels like the `bb` / `bbin` juggernaut has kind of answered the problems that `plum` was trying to tackle?

**Comment by lilactown** [comment]
Yeah I think so. bb is a much better way to do this
