### ISSUE TITLE
iapetos (prometheus lib/client)

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/meta#31]
https://github.com/xsc/iapetos

I have asked @xsc if we can move his wonderfull client to clj-commons. I would also like to help co-maintain if possible

**Comment by lread** [comment]
I don’t know if this of any help @MalloZup, but here is my request to the same author to perhaps bring his wonderful rewrite-clj over to clj-commons: https://github.com/xsc/rewrite-clj/issues/77

**Comment by MalloZup** [comment]
Thx @lread!

**Comment by MalloZup** [comment]
closing

**Comment by MalloZup** [comment]
project was merged thx!
