### ISSUE TITLE
oraclejdk dep in travis build

### ISSUE THREAD

**Issue by MalloZup** [clj-commons/meta#32]
I think we should switch to use openjdk8 
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/2

jfyi

**Comment by slipset** [comment]
I'd rather we changed to CircleCI, as most other clj-commons projects is on Circle.

**Comment by MalloZup** [comment]
yep, I will try to do it then thx

**Comment by slipset** [comment]
If you could add a build status badge in the readme as well, that would be stellar!

**Comment by MalloZup** [comment]
yep
