### ISSUE TITLE
useful should be moved to circle

### ISSUE THREAD

**Issue by slipset** [clj-commons/meta#36]

**Comment by slipset** [comment]
done

**Comment by rborer** [comment]
Hi, maintainer of tentacles here. Sorry to post here but I couldn't find the issue related to migrating tentacles to CircleCI.

I was wondering if there is any reason to stick with leiningen 2.7.1 :thinking: ? Looking at https://hub.docker.com/r/circleci/clojure I see that there is a tag available for version 2.9.1.

**Comment by slipset** [comment]
Sorry, created now, #47
