### ISSUE TITLE
tentacles should be moved to circle

### ISSUE THREAD

**Issue by slipset** [clj-commons/meta#47]

**Comment by slipset** [comment]
@rborer The only reason I set up stuff with lein-2.7.1 is that it's the default config from Circle.

**Comment by rborer** [comment]
@slipset ok thanks for the clarification. I'll try with 2.9.1 & see how it goes (hopefully well :wink: ).

**Comment by MalloZup** [comment]
@rborer  we have already circleci set-up for other proejcts, feel free to take inspiration from there

**Comment by rborer** [comment]
Seems to work fine with leiningen 2.9.1. @slipset you can close this issue as you already did the initial migration (and I think it is complete).
