### ISSUE TITLE
Bumping versions to at least 1.0.0

### ISSUE THREAD

**Issue by dijonkitchen** [clj-commons/meta#51]
Seems like there are a bunch of old, robust libraries in here and elsewhere in the Clojure ecosystem that are still at a semantic major version of 0 when they probably have had a relied upon, stable, public API for a long time. 

Is it worth bumping these to at least semantic version 1.0.0? It would signal to end consumers that these are actually stable libraries, consistent with the wider programming ecosystem. 

Reference:
https://semver.org/#spec-item-4

**Comment by danielcompton** [comment]
I think this should be up to the maintainers of the projects. It seems like a reasonable thing to do, if the intention is for the API to stabilise.

**Comment by dijonkitchen** [comment]
I thought clj-commons was going to be the new maintainer for their projects.

**Comment by danielcompton** [comment]
Sorry, what I mean is that maintainers of specific projects within clj-commons should be free to set the version as appropriate, based on their understanding of the project's maturity and needs. I'm not against moving to 1.0.0, I just don't think it needs to be a rule.

**Comment by dijonkitchen** [comment]
OK, that's fine. I'll leave this here for those maintainers then. 

I think most projects are stable and the greater developer community would benefit from using a consistent semantic versioning technique with version 1.0.0+ for stable libraries.

**Comment by dijonkitchen** [comment]
FYI, looks like this is gaining traction. 

https://insideclojure.org/2020/02/18/lib-version/

**Comment by seancorfield** [comment]
Since this is up to the project maintainers, I'm going to close this out.
