### ISSUE TITLE
seesaw

### ISSUE THREAD

**Issue by torkus** [clj-commons/meta#54]
I've broached the topic of transferring [seesaw](https://github.com/daveray/seesaw) to clj-commons here: https://github.com/daveray/seesaw/issues/224

@daveray has given his approval

Seesaw is a broad and deep library and I won't pretend I'm an expert on it's insides, but I'm willing to triage tickets, switch it to circle-ci, bump dependencies, investigate bugs, coordinate with others, etc.

**Comment by slipset** [comment]
Doing a very cursory due diligence, it seems to fit nicely with clj-commons, as it has both a bunch of stars on GitHub, and a substantial amount of downloads in Clojars.

I'll add @daveray and yourself to the org so we can transfer the repo.

**Comment by torkus** [comment]
thank you, @slipset . Invitation accepted.

**Comment by torkus** [comment]
@slipset, what's the current status on this? Are we blocked by something?

**Comment by slipset** [comment]
We're waiting for @daveray to transfer the project. Only he can do that.

**Comment by torkus** [comment]
ah, no worries. cheers

**Comment by daveray** [comment]
@slipset Sorry. I wasn't aware anyone was waiting for me to do anything. Is this just "Settings/Danger Zone/Transfer"?

**Comment by slipset** [comment]
@daveray Yes

**Comment by divs1210** [comment]
hi @daveray is this blocked on something?

**Comment by torkus** [comment]
(just an FYI, I don't have the time anymore to take on any maintenance duties myself but being part of clojure commons the project may find other maintainers)

**Comment by mfru** [comment]
hi, is there a reason why the transfer wasn't completed yet?

**Comment by daveray** [comment]
Just did the transfer. Let me know if anything else is needed. Sorry about the delay.
