### ISSUE TITLE
Pomegranate

### ISSUE THREAD

**Issue by glts** [clj-commons/meta#56]
According to [this comment](https://github.com/cemerick/pomegranate/pull/116#issuecomment-552039704), Pomegranate can be considered abandoned or provided as-is.

Pomegranate is a critical Clojure library, it is a core dependency of Leiningen.

We should consider forking Pomegranate under the clj-commons organisation.

**Comment by slipset** [comment]
I think this is a reasonable library to take on, but we’d probably need some help in actively maintaining it, if that’s needed. 

Any clue to why @cemerick would want to fork and not transfer the repo?

**Comment by glts** [comment]
Forking seems like the proper action for such a situation, no? At least that would preserve cemerick's original authorship in the record, which I think is fair.

**Comment by slipset** [comment]
Forking doesn’t do that, transfers do.

**Comment by borkdude** [comment]
Maybe asking explicitly in the latest comment works better.

**Comment by cemerick** [comment]
Please don't read my comment as carrying any particular preference re: how "ownership" of the code base is changed. I was just using "fork" as a loose shorthand, and I'm not too worried about credit blame, the commit history is there 😁

**Comment by danielcompton** [comment]
This seems like a good candidate for adoption, @cemerick would you like to transfer Pomegranate into clj-commons? We'd be happy to accept it.

**Comment by cemerick** [comment]
Apparently I need "permission to create public repositories on clj-commons"?

**Comment by danielcompton** [comment]
Invited!

**Comment by cemerick** [comment]
The repo has been transferred. :smile:
