### ISSUE TITLE
Add Clojurists Together as Github sponsor link for organization and its project

### ISSUE THREAD

**Issue by dijonkitchen** [clj-commons/meta#58]
https://www.clojuriststogether.org/developers/

**Comment by danielcompton** [comment]
Sorry, could you explain more what is the suggested action here? clj-commons and Clojurists Together are related in that I am part of both of them, but I don't think they have any other connection.

**Comment by dijonkitchen** [comment]
I meant to add a sponsor badge to direct more people to donating to Clojurists Together. 

https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by slipset** [comment]
clj-commons doesn't accept sponsorship as an organization, but anyone is free to sponsor any of the devs maintaining the libs we maintain. Having said that, I'd be very open to a nice button encouraging people sponsor Clojurists Together.
