### ISSUE TITLE
clj-digest

### ISSUE THREAD

**Issue by tebeka** [clj-commons/meta#61]
I'm the author of [clj-digest](https://github.com/tebeka/clj-digest). It's been a while sinec I've worked with Clojure and recently [a request came up](https://github.com/tebeka/clj-digest/issues/12) that I'm not sure how to solve.

@borkdude suggested I'll move the package here, is this possible?

**Comment by slipset** [comment]
Looking at the stats for `cli-digest` I think it would be reasonable for clj-commons to take on `clj-digest`. Furthermore, I see that there are several libs in the same area of functionality, so it would probably be nice to have a common lib.
I'll invite you to the clj-commons org so you can transfer the repo

**Comment by slipset** [comment]
Yes, you need to transfer that røo from yourself to clj-commons. You'll find transfer somewhere in the settings bit of your repo.

**Comment by tebeka** [comment]
In transfer ...
