### ISSUE TITLE
Dirigiste and Gloss

### ISSUE THREAD

**Issue by KingMob** [clj-commons/meta#62]
When we originally started porting over Zach Tellman's old repos, we left Dirigiste and Gloss alone. I'd like to suggest they be pulled into clj-commons.

Dirigiste is pretty stable, but looking down the road, I'd like to make it compatible with Project Loom's virtual threads, since Manifold depends on it, and may want to make use of them.

Gloss has a reflection bug that both I and another have run into in modern JVM versions, requiring local forks. It shouldn't need much maintenance otherwise.

Of the two, Dirigiste is more important, since it's a dep of Aleph and Manifold.

**Comment by slipset** [comment]
Sounds reasonable, @ztellman what do you think?

**Comment by KingMob** [comment]
@casselc also encountered the error, and said he'd consider helping with Gloss.

**Comment by ztellman** [comment]
Sure, fine by me.

**Comment by ztellman** [comment]
Both are now transferred to clj-commons.  

On a tangential note, I've recently stepped back to part-time at my job to work on a book, but will also give me some more time to provide support for the new maintainers of these projects.  I'll need to give some thought as to how to structure this, but if either of you have suggestions I'd be interested to hear them.

**Comment by KingMob** [comment]
@ztellman I think a lot depends on how much time you have/want to spend on helping. There's a long list of things that would help, from PR review, documenting past decisions and internals, consulting on future directions, answering questions, etc.

I would suggest something like semi-regular office hours on Slack, but I'm moving to Indonesia on Sunday, and the TZ difference may be tricky. Realistically, 95% of any work being done is by me when I get a spare moment, but being more available might help get more people involved. We could really use someone with more familiarity with Netty for Aleph.

Zach, I think it's up to you to decide what your assistance level is, and I'll work around that.

**Comment by casselc** [comment]
Sorry for the late response, I've been on vacation the past couple of weeks and just getting caught up on messages. I would be happy to help with maintaining Gloss. As I mentioned to @KingMob, I don't have a lot of Clojure experience, but I also don't expect many code changes will be needed. I've been doing some networking side projects to learn Clojure, so my initial thought was just to use that experience to flesh out documentation and add examples of more involved protocol/format implementations. As a concrete example, before I left, I was working on a torrent client using Gloss and Aleph - so I was considering reusing my Bencode implementation and elaborating on the existing echo example to show how to go from that to a simple NREPL client/server. 

I would certainly appreciate any time @ztellman is able to share, but with my current level of experience I want to make sure I don't waste it with things I could get answered in the Clojurians Slack, so I would be fine with some form of async Q&A unless/until some significant change is required.

As a general matter, I have a working CircleCI build in my fork if that's needed for Gloss.
