### ISSUE TITLE
Hiccup

### ISSUE THREAD

**Issue by holyjak** [clj-commons/meta#64]
Looking at the number of open issues nad PRs in https://github.com/weavejester/hiccup/, I am thinking that @weavejester might be interested in transferring it to clj-commons, perhaps?

**Comment by weavejester** [comment]
Hiccup could certainly do with some attention, but regarding the PR backlog, most of them are waiting on the developer who initially opened them. I've merged the couple that were done; all the others are failing CI or waiting for changes to be made after code review. I've added tags to make the status clearer.

**Comment by holyjak** [comment]
I understand that you are happy to keep Hiccup where it is, correct?

**Comment by weavejester** [comment]
I'm not sure what advantage there'd be to moving it, so for now I'm happy to keep it where it is.
