### ISSUE TITLE
Adopt clayppol library in clj-commons?

### ISSUE THREAD

**Issue by ieugen** [clj-commons/meta#65]
Hello I would like to open the discussion about adopting claypool in clj-commons.
I thought about this after the discussion in https://github.com/TheClimateCorporation/claypoole/issues/52 .

Maybe @leon-barrett thinks this is a good idea.

I would be open to helping out with the process.
Perhaps we can open discussions to transfer the repository instead of forking it.

**Comment by leon-barrett** [comment]
Yes, I am able to provide some help in moving the repo.

**Comment by slipset** [comment]
So I'd need to add @leon-barrett as a member to clj-commons so that the repo can be transferred. I would appreciate, however, that we get an ok from The Climate Corp before we do the transfer, as it is under their org.

**Comment by ieugen** [comment]
Yes, @leon-barrett  commented on the original issue - he is going to try and contact the company to transfer the repo. 

Would be nice to have this transferred and updated. 
I can help with migrating to deps.edn and some other maintenance.

Let me know if you need my help.

**Comment by leon-barrett** [comment]
@slipset I've got a Climate Corp manager who's happy to make the transfer. Can he transfer it to your account, and then you can transfer it to clj-commons? https://github.com/TheClimateCorporation/claypoole/issues/52#issuecomment-1020162165

**Comment by slipset** [comment]
@leon-barrett and @ieugen  I've added you as a member of clj-commons
