### ISSUE TITLE
onyx

### ISSUE THREAD

**Issue by 13kay** [clj-commons/meta#68]
is there a chance on onyx?
https://github.com/onyx-platform/onyx/issues/887

**Comment by danielcompton** [comment]
I'd want to see commitment from a few maintainers to work on it. Onyx is a pretty large project. What would the benefit of moving this to clj-commons over adding new maintainers to onyx/starting a fork?

I see a big benefit of clj-commons to be able to make small fixes to stable, mostly done projects (among other things). But Onyx doesn't seem "mostly done" to me, but I could be wrong.

**Comment by slipset** [comment]
I agree with @danielcompton on this one. Onyx is a bit more than a useful library, more akin to [aleph](https://github.com/clj-commons/aleph) where we are fortunate to have @KingMob et al who are basically running the project. For us to take on onyx, I think we'd need someone like that, but then again, it seems to me that @MichaelDrogalis and @lbradstreet have shown that they're happy to have new maintainers take on onyx over at [onyx](https://github.com/onyx-platform/onyx), so the value of cli-commons adopting onyx seems minimal.
