### ISSUE TITLE
clj-ssh

### ISSUE THREAD

**Issue by martinklepsch** [clj-commons/meta#7]
https://github.com/hugoduncan/clj-ssh

Seems unmaintained but useful to the community. Regularly has 1000+ downloads. 

At the time of writing:

- 4 out of 6 PRs are trivial to merge/close
- 22 open issues with no labels (needs triage)

**Comment by slipset** [comment]
I've reached out to @hugoduncan

**Comment by slipset** [comment]
It's on it's way :)

**Comment by orestis** [comment]
Was about to open an issue for this :) anyway I can help speed things along?

**Comment by slipset** [comment]
clj-ssh has now arrived :)

**Comment by MalloZup** [comment]
@slipset nice one thx!
