### ISSUE TITLE
Kibit

### ISSUE THREAD

**Issue by NoahTheDuke** [clj-commons/meta#71]
[Kibit](https://github.com/jonase/kibit) is one of the oldest linters for Clojure, created in 2012. It used to have fairly active development, but as folks have moved on or focused on other projects, that effort has slowed. As such, it's not had a proper release in 2.5 years and hasn't had a commit in over a year, with bugs like the inability to read `:as-alias`ed keywords rendering some files un-lintable, and PRs sitting open without activity for multiple years.

I'm willing to steward it. I don't have any experience with the codebase but I'm looking to use it at my workplace and would prefer to put my energy towards the greater community than fork and develop an in-house version.

@jonase and @danielcompton, do you two have any thoughts on this?

**Comment by lread** [comment]
@NoahTheDuke I ask out of ignorance: would Kibit offer any advantages/features over the currently actively maintained linters [clj-kondo](https://github.com/clj-kondo/clj-kondo) and [eastwood](https://github.com/jonase/eastwood)?

**Comment by NoahTheDuke** [comment]
That's a good question. I think the difference is scope and desired area of focus. clj-kondo and eastwood are fundamentally designed to catch errors. Both have expanded to catch style linters as well (such as nested lets), but the majority of both of their linters are focused on catching errors in code. Kibit is singularly focused on "idiomatic" code substitutions: here is functioning code, here is a suggestion on how to rewrite it to be more aligned with the greater clojure community's idioms. These kinds of style linters are possible in clj-kondo and eastwood but I think they're more awkward to implement.

To compare, here are how the 2 linters implement the same checks:

| lint | kibit | clj-kondo | eastwood
| - | - | - | - |
| `(not (empty? x))` | [link][kibit-not-empty] | [`:not-empty?`][clj-kondo-not-empty] | N/A |
| `(-> x)` | [link][kibit-redundant-call] | [`:redundant-call`][clj-kondo-redundant-call] | [`:suspicious-expression`][eastwood-suspicious-expression]

[kibit-not-empty]: https://github.com/jonase/kibit/blob/be27e6db625564d045e71a6e13e459eb7651813b/kibit/src/kibit/rules/collections.clj#L17
[kibit-redundant-call]: https://github.com/jonase/kibit/blob/be27e6db625564d045e71a6e13e459eb7651813b/kibit/src/kibit/rules/misc.clj#L79

[clj-kondo-not-empty]: https://github.com/clj-kondo/clj-kondo/blob/5db942f19916f98e8d21b4f787f37f3be0e0d45d/src/clj_kondo/impl/analyzer.clj#L1526
[clj-kondo-redundant-call]: https://github.com/clj-kondo/clj-kondo/blob/5db942f19916f98e8d21b4f787f37f3be0e0d45d/src/clj_kondo/impl/linters.clj#L448

[eastwood-suspicious-expression]: https://github.com/jonase/eastwood/blob/6c57aaa1681b0e7e248b5c27c3cc1b90d9164b0c/src/eastwood/linters/typos.clj#L541

I had originally intended to find more than 2 examples of the overlaps, but kibit covers a lot of ground that clj-kondo and eastwood don't because it's focused on suggesting built-in alternatives to given forms, which clj-kondo only has minimal support for and eastwood generally doesn't handle at all.

For example, only 3 of the 22 linters in [this file](https://github.com/jonase/kibit/blob/be27e6db625564d045e71a6e13e459eb7651813b/kibit/src/kibit/rules/misc.clj) are covered by the other two, unneeded anonymous function and unneeded threading macros. These style linters aren't dramatic but they're helpful in using the "best"/idiomatic way to write certain forms.

I see the future of kibit as updating the internals to handle disabling rules from a config file or inline somehow, fixing the existing bugs, and adding/updating the set of linters to what is considered "best practices".

**Comment by NoahTheDuke** [comment]
I've emailed @jonase about transferring or making me a maintainer which would render the transfer unnecessary. Hopefully we'll get an answer soon!

**Comment by slipset** [comment]
I've invited @jonase to the org so he should be able to transfer kibit to clj-commons

**Comment by danielcompton** [comment]
I'm supportive of this, over the last few years I haven't been able to give Kibit the attention it deserves. Moving to cli-commons seems like a good outcome, though I'll defer to @jonase as it's ultimately his project.

**Comment by jonase** [comment]
I made the transfer: https://github.com/clj-commons/kibit
