### ISSUE TITLE
clojure-humanize

### ISSUE THREAD

**Issue by hlship** [clj-commons/meta#72]
I've been a long-time user of https://github.com/trhura/clojure-humanize, a useful library that has been long neglected as the original author has [moved on](https://github.com/trhura/clojure-humanize/issues/26#issuecomment-1225079929) and ceded admin rights to myself and @kongeor.

We've already updated dependencies and setup up a deps.edn build, in advance of a 0.3 release (last release was 0.2.2 back in 2016).  I feel that many Clojure projects that wish to excel in providing top-notch feedback to users, would benefit from making use of clojure-humanize, and bringing it under the clj-commons umbrella would spur adoption of the library.

**Comment by slipset** [comment]
Seems ok to me? Feel free to do the transfer.

**Comment by seancorfield** [comment]
This has been transferred in so I guess this can be closed now?
