### ISSUE TITLE
clojuredocs.org

### ISSUE THREAD

**Issue by port19x** [clj-commons/meta#73]
[clojuredocs](https://clojuredocs.org/) likely needs no introduction.
The repo hasn't seen a commit in a year despite large easy to fix issues like a [dead link](https://github.com/zk/clojuredocs/pull/235) and linking to a now [outdated clojure](https://github.com/zk/clojuredocs/pull/246) release as latest.

- [Repo](https://github.com/zk/clojuredocs)
- [Activity](https://github.com/zk/clojuredocs/graphs/contributors)
- [Current Maintainer](https://github.com/zk)

**Comment by seancorfield** [comment]
There's quite a bit of infrastructure involved with clojuredocs.org so it's not just a repo to maintainer, there's AWS costs and a deployment process and tooling etc.

I don't know how this is all currently managed but clj-commons doesn't have funding support to run infrastructure beyond GitHub Pages really.

That said, we can reach out to the maintainer and see what the current state of play is.
