### ISSUE TITLE
I'd like to help with maintenance of Kibit and Hickory

### ISSUE THREAD

**Issue by port19x** [clj-commons/meta#74]
I'd be interested in co-maintaining [hickory](https://github.com/clj-commons/hickory) and [kibit](https://github.com/clj-commons/kibit).
Is slack required to contribute to clj-commons?
I don't have a slack account and would prefer not to open one just for clojure.

As a baseline I can guarantee frequent activity and good triage of issues and PRs.
I probably won't contribute large portions of self-written code.
As for hickory, I have a lot of domain knowledge from several years of writing and maintaining web scrapers.

Plans for hickory:

- Implement: clj-commons/hickory#76
- Fix: clj-commons/hickory#77
- A printer function to visualize the dom tree from hiccup and hickory
- Perhaps more printer functions for hiccup and hickory if useful

Plans for kibit:

- Add docs to readme: clj-commons/kibit#221
- Generally brush up on docs

Check my [github profile](https://github.com/port19x) to assess my activity and clojure skills.
Check out [ani-cli](https://github.com/pystardust/ani-cli) to assess my maintenance style.

**Comment by borkdude** [comment]
@port19x Sounds good!

A Slack account is not mandatory but I think it will help a lot to get in closer contact with existing maintainers. A good starting point would be to post a message in the clj-commons channel.

I'm going to ping @NoahTheDuke here as the new kibit maintainer. I'm not sure who the new hickory maintainer is, would that be @slipset?

**Comment by NoahTheDuke** [comment]
Hey @port19x! I would love to have you join up. Will be good to have someone who actively uses Kibit contributing.
