### ISSUE TITLE
io.aviso/pretty

### ISSUE THREAD

**Issue by hlship** [clj-commons/meta#75]
I'm the original author of [io.aviso/pretty](https://github.com/AvisoNovate/pretty), it's actually some of my first Clojure code.  Easily my most popular bit of code ... over 16M downloads at Clojars.

I have long considered creating an incompatible version 2, to address a fundamental failure in how the ANSI code support works; it locks the decision to enable or disable ANSI colors in at compilation time, not execution time, which makes it less useful with AOT or Graal compilation.  Fixing that properly can't be done in a backwards compatible way.

I've been working on a [PR](https://github.com/AvisoNovate/pretty/pull/92) to refactor and streamline the namespaces and address a number of other long-term concerns.

I've been unable to connect with any of the folks from Aviso - I think they may no longer be a Clojure shop -  but the code is ASL 2.0 and I have admin rights to the existing repo, so moving it over would not be an issue.

**Comment by danielcompton** [comment]
Sounds great to me! I love pretty, and think this would be awesome to do.

**Comment by seancorfield** [comment]
This has been transferred in so if you're happy with that @hlship this issue can be closed?
