### ISSUE TITLE
Naming the maintenance project

### ISSUE THREAD

**Issue by danielcompton** [clj-commons/meta#8]
I think it would be useful to have a name to give to this sub-project of cli-commons which maintains libraries and tools when the original maintainer doesn't have time for them anymore. I have a few ideas, but am not in love with any of them. Ideas welcome!

* Nursery
* Resthome
* Archive
* Maintenance Shed
* Second Wind

**Comment by slipset** [comment]
Just so I understand, you're suggesting renaming `wishlist` to any of the above?

**Comment by danielcompton** [comment]
Not really this specific repo, but the general umbrella term for the work of taking over maintenance of existing libraries when their maintainers have moved on.

**Comment by jcf** [comment]
Couple of ideas:

Adoption, assist, continue, renew, extend…

If I understand what the name is supposed to convey, you want to communicate that we’re prolonging and renewing. Archiving or rest homing suggest an end to something, whereas this is an extension and something positive.

I would note at least one issue in this repo appears to relate to a maintained library… not sure how best to handle that as a community. Maybe using GitHub issues isn’t the best approach?

**Comment by Heliosmaster** [comment]
For the general term to use I think `adoption` is a sound one. It universally conveys the idea of embracing something and taking care of it (for some time at least) which is the purpose of this.

And about this repo, why not take a hint from Wikimedia and just call it `meta`? In my mind it clarifies that it's not a project per se, but a repo about everything else related to clj-commons. That includes discussions such as this, and governance models and whatnot.

**Comment by danielcompton** [comment]
> For the general term to use I think adoption is a sound one. 

Yeah, I think it makes sense to me too.

> And about this repo, why not take a hint from Wikimedia and just call it meta?

Great idea, I've just updated it now.

**Comment by seancorfield** [comment]
Any further action/input needed, or can this be closed out now the repo has been renamed to `meta`?

**Comment by danielcompton** [comment]
Nope!
